portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

portfolio/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from . import views

app_name = 'portfolio'


urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('coding/', views.Coding.as_view(), name='coding'),
    path('art/', views.Art.as_view(), name='art')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('portfolio.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/models.py
from django.utils.text import slugify
from django.conf import settings
from django.db import models
from PIL import Image
import os



# Create your models here.

class CodingPhoto(models.Model):
    class Meta:
        verbose_name = 'Code photo'

    image = models.ImageField(upload_to='coding/main_photo/%Y/%m')
    name = models.CharField(max_length=25)
    slug = models.SlugField(unique=True, blank=True, null=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.name)}-{self.pk}'
            self.slug = slug

        super().save(*args, **kwargs)
    

class Photo(models.Model):
    class Meta:
        verbose_name = 'Home photo'

    image = models.ImageField(upload_to='main_photo/%Y/%m')
    name = models.CharField(max_length=25)
    slug = models.SlugField(unique=True, blank=True, null=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.name)}-{self.pk}'
            self.slug = slug

        super().save(*args, **kwargs)


class ArtProjects(models.Model):
    class Meta:
        verbose_name = 'Draw'
        verbose_name_plural = 'Draws'

    name = models.CharField(max_length=25)
    short_description = models.TextField(max_length=255)
    long_description = models.TextField()
    image = models.ImageField(upload_to='art/projects/%Y/%m', unique=True)
    slug = models.SlugField(unique=True, blank=True, null=True)

    @staticmethod  # <- there is no 'self' in the method
    def resize_image(img, new_size=(1080, 1080)):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if (original_width, original_height) <= new_size:
            img_pil.close()
            return

        new_img = img_pil.resize(new_size, Image.LANCZOS)
        new_img.save(img_full_path, optimize=True, quality=50)


    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.name)}-{self.pk}'
            self.slug = slug

        super().save(*args, **kwargs)

        target_size = (1080, 1080)

        if self.image:
            self.resize_image(self.image, target_size)

    def __str__(self):
        return self.name


class CodeProjects(models.Model):
    class Meta:
        verbose_name = 'Code project'
        verbose_name_plural = 'Code projects'

    name = models.CharField(max_length=25)
    short_description = models.TextField(max_length=255)
    long_description = models.TextField()
    image = models.ImageField(upload_to='coding/projects/%Y/%m', unique=True)
    slug = models.SlugField(unique=True, blank=True, null=True)

    @staticmethod  # <- there is no 'self' in the method
    def resize_image(img, new_size=(1080, 1080)):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if (original_width, original_height) <= new_size:
            img_pil.close()
            return

        new_img = img_pil.resize(new_size, Image.LANCZOS)
        new_img.save(img_full_path, optimize=True, quality=50)


    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.name)}-{self.pk}'
            self.slug = slug

        super().save(*args, **kwargs)

        target_size = (1080, 1080)

        if self.image:
            self.resize_image(self.image, target_size)

    def __str__(self):
        return self.name

class ArtPhoto(models.Model):
    class Meta:
        verbose_name = 'Art photo'

    image = models.ImageField(upload_to='art/main_photo/%Y/%m')
    name = models.CharField(max_length=25)
    slug = models.SlugField(unique=True, blank=True, null=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.name)}-{self.pk}'
            self.slug = slug

        super().save(*args, **kwargs)
    

portfolio/views.py
from django.shortcuts import render, get_object_or_404
from . import models
from django.views import View
from django.http import HttpResponse

class Home(View):
    template_name = 'portfolio/home.html'

    def get(self, request, *args, **kwargs):
        principal_photo = models.Photo.objects.first()
        return render(request, self.template_name, {'principal_photo': principal_photo})

    
class Coding(View):
    template_name = 'portfolio/coding.html'
    
    def get(self, request, *args, **kwargs):
        principal_photo = models.CodingPhoto.objects.first()
        # get the value of the key 'slug', that came from the model
        slug = kwargs.get('slug')
        context = {'principal_photo': principal_photo}

        if slug:
            project = get_object_or_404(models.CodeProjects, slug=slug)
            context['project'] = project
            return render(self.request, self.template_name, context)
        code_projects = models.CodeProjects.objects.all()
        context['code_projects'] = code_projects  
        return render(self.request, self.template_name,context)


class Art(View):
    template_name = 'portfolio/art.html'

    def get(self, request, *args, **kwargs):
        # get the value of the key 'slug', that came from the model
        slug = kwargs.get('slug')
        principal_photo = models.ArtPhoto.objects.first()
        context = {'principal_photo': principal_photo}
        
        if slug:
            project = get_object_or_404(models.ArtProjects, slug=slug)
            context['project'] = project
            return render(self.request, self.template_name, context)
        art_projects = models.ArtProjects.objects.order_by('-id').all()
        context['art_projects'] = art_projects
        return render(self.request, self.template_name, context)

portfolio/templates/portfolio/art.html
{% extends "base.html" %} {% block title %}Arte - {% endblock title %}
<!--disable-eslint-->
{% block content %}
<!--disable-eslint-->

<div class="gray-section">
  <section class="section main-content">
    <div class="grid">
      <h1 class="title">Arte e projetos artísticos</h1>
      {% if principal_photo %}
      <img
        class="me"
        src="{{principal_photo.image.url}}"
        alt="{{principal_photo.name}}"
      />
      {% else %}
      <h1 class="title">No photo found</h1>
      {% endif %}
    </div>
    <div class="text-content">
      <p>Um pouco sobre minha atividade favorita.</p>
    </div>
  </section>
</div>

<div class="black-section">
  <section class="section main-content">
    <h1 class="sections-title">Projetos</h1>
    <p class="text-content">
      Comecei a desenhar desde os 7 anos. No começo nunca tive tanta habilidade,
      mas de tantos anos praticando, fui me aperfeiçoando e usando mais da
      criatividade. Nesses últimos anos tenho buscado fazer projetos mais
      autorais, sem cópias de retratos pela internet. <br />
      Desenhar ou qualquer processo artístico é muito mais do que ver o
      resultado, e sim sentir todo o processo de algo 'imaginário' se
      materializar.
    </p>
    <div class="grid-projects">
      {% for project in art_projects %}
      <div class="grid-projects-item">
        <h1 class="title-project">{{project.name}}</h1>
        <img
          class="img-art"
          src="{{project.image.url}}"
          alt="{{project.name}}"
        />
        <p class="text-description">{{project.short_description}}</p>
      </div>
      {% endfor %}
    </div>
  </section>
</div>
{% endblock content %}

portfolio/templates/portfolio/coding.html
{% extends "base.html" %} {% block title %}Programação - {% endblock title %}
<!--disable-eslint-->
{% block content %}
<!--disable-eslint-->
<div class="black-section">
  <section class="section main-content">
    <div class="grid">
      <h1 class="title">Programação e desenvolvimento</h1>
      {% if principal_photo %}
      <img
        class="me"
        src="{{principal_photo.image.url}}"
        alt="{{principal_photo.name}}"
      />
      {% else %}
      <h1 class="title">No photo found</h1>
      {% endif %}
    </div>
    <div class="text-content">
      <p>
        O que mais gosto nesse meio, <br />e como comecei a me interessar pelo
        assunto!
      </p>
    </div>
  </section>
</div>

<div class="gray-section">
  <section class="section main-content">
    <h1 class="sections-title">O começo</h1>
    <p class="text-content">
      Eu nunca tive grande apreço por essa área, até ter a oportunidade de
      estudar pela escola. Não pude, mas continuei me dedicando a aprender por
      conta própria. <br />
      Atualmente tenho muito gosto em usar JavaScript e Python, e estou
      estudando e praticando para me tornar um desenvolvedor FullStack.
    </p>
  </section>
</div>

<div class="black-section">
  <section class="section main-content">
    <h1 class="sections-title">Projetos</h1>
    <p class="text-content">
      Meus projetos envolvendo o desenvolvimento e programação. A maioria deles
      eu sempre continuo atualizando e modificando algo, seja no front-end ou no
      back-end. <br />
      Meu intuito agora é fazer o deploy de todos, ou pelo menos os mais
      aplicáveis na vida real.
    </p>
    <div class="grid-projects">
      {% for project in code_projects %}
      <div class="grid-projects-item">
        <h1 class="title-project">{{project.name}}</h1>
        <img
          class="img-art"
          src="{{project.image.url}}"
          alt="{{project.name}}"
        />
        <p class="text-description">{{project.short_description}}</p>
      </div>
      {% endfor %}
    </div>
  </section>
</div>
{% endblock content %}

portfolio/templates/portfolio/home.html
{% extends "base.html" %} {% block content %}

<div class="gray-section">
  <section class="section main-content">
    <div class="grid">
      <h1 class="title">
        Olá, meu nome é <bold class="text-shadow">Finotti</bold>
      </h1>
      {% if principal_photo %}
      <img
        class="me"
        src="{{principal_photo.image.url}}"
        alt="Principal Photo"
      />
      {% else %}
      <h1 class="title">No photo found</h1>
      {% endif %}
    </div>
    <div class="text-content">
      <p>Artista, desenvolvedor e futuro poliglota.</p>
    </div>
  </section>
</div>

<div class="black-section">
  <section id="me" class="section main-content">
    <h1 class="sections-title">Sobre</h1>
    <p class="text-content">
      Sou Isaac, um estudante de Eletroeletrônica no SENAI e um aspirante ao
      título de desenvolvedor FullStack. Sou fluente em inglês e tenho
      conhecimento básico no idioma russo (A1). Minha paixão por arte é
      refletida em projetos criativos. Esse portifólio mostra meus projetos
      artísticos e meus projetos desenvolvidos por mim durante algum curso ou
      por conta própria, demonstrando meu compromisso com os dois assuntos,
      buscando sempre inovação. Sinta-se livre para explorá-lo e me contatar
      caso queira colaborar com algo.
    </p>
  </section>
</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "partials/_head.html" %}

    <title>{% block title %}{% endblock title %} Finotti</title>
  </head>

  <body>
    {% include "partials/_nav.html" %}
    <!--disable-eslint-->
    {% block content %}{% endblock content %}
    <!--disable-eslint-->
    {% include "partials/_footer.html"%}
  </body>
</html>

templates/partials/_footer.html
{% load static %}
<footer>
  <div class="footer">
    <h2>IFinotti</h2>
    <ul>
      <li>
        <a href="https://github.com/IFinotti" target="_blank"
          ><i class="fa fa-github-square"></i
        ></a>
      </li>
      <li>
        <a href="mailto:imisaac2807@gmail.com"
          ><i class="fa fa-envelope" aria-hidden="true"></i
        ></a>
      </li>
      <li>
        <a href="https://www.linkedin.com/in/isaac-finotti/" target="_blank"
          ><i class="fa">&#xf0e1;</i></a
        >
      </li>
      <li>
        <a
          href="https://www.youtube.com/channel/UCiV4BWOJSKLDnlrjLpwLm4g"
          target="_blank"
        >
          <i class="fa fa-youtube"></i>
        </a>
      </li>
    </ul>

    <!-- prettier-ignore -->
    <p>
      &copy; 2024 Meu portifólio. Todos os direitos reservados. | Desenvolvido por  <a href="">Finotti</a>
    </p>
  </div>
</footer>

<a class="back-to-top" href="#">⏶︎</a>

<script src="{% static 'custom/js/scripts.js' %}"></script>
<script src="{% static 'custom/js/scrollReveal.js' %}"></script>

templates/partials/_head.html
{% load static %}

<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  rel="stylesheet"
  href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"
/>

<link
  href="https://fonts.googleapis.com/css2?family=Prompt:wght@200;400&display=swap"
  rel="stylesheet"
/>
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Martian+Mono&display=swap"
  rel="stylesheet"
/>
<script src="https://unpkg.com/scrollreveal"></script>
<link rel="stylesheet" href="../static/custom/css/styles.css" />
<link rel="stylesheet" href="../static/custom/css/scrollReveal.css" />

templates/partials/_nav.html
{% load static %}
<input id="close-menu" class="close-menu" type="checkbox" />
<label class="close-menu-label" for="close-menu" title="Close menu"></label>
<nav>
  <div class="menu">
    <h3 class="main-title">
      <a href="{% url 'portfolio:home' %}">Finotti</a>
    </h3>
    <ul>
      <li>
        <a class="menu-link" href="{% url 'portfolio:coding' %}">Programação</a>
      </li>
      <li><a class="menu-link" href="{% url 'portfolio:art' %}">Arte</a></li>
      <li>
        <a
          class="menu-link"
          href="https://galleryfinotti.pythonanywhere.com"
          target="_blank"
          >Galeria</a
        >
      </li>
    </ul>
  </div>
</nav>